name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  BITCOIN_REST_ENDPOINT: "https://btc.visvirial.com/rest/"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache ~/.cargo
      uses: actions/cache@v2
      with:
        path: ${{ env.HOME }}/.cargo
        key: cargo-${{ runner.os }}
        restore-keys: |
          cargo-

    - name: Configure sccache
      uses: visvirial/sccache-action@v1.0.0

    - name: Build
      run: cargo build --verbose

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1

